version: 0.0
os: linux
files:
  - source: /src
    destination: /home/bitnami/app
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
    