version: 0.2

phases:
  build:
    commands:
      - npm install
artifacts:
  files:
    - src/*
    - src/**/*
    - node_modules/*
    - node_modules/**/*
  name: my-library-$(date +%Y-%m-%d-%H:%M:%S).zip